/* actions/registry.ts — data-driven action definitions. */
import { beforeCapture } from '../platform.js';

export interface Action {
  id: string;
  title: string;
  hint: string;
  icon: string;
  kw: string;
  exec?: string;
  payload?: Record<string, unknown>;
  pageOnly?: boolean;
  requires?: string;
  before?: () => unknown;
  local?: () => unknown;
}

export const ACTIONS: Action[] = [
  { id: 'new-tab', title: 'New Tab', hint: 'Action', icon: 'plus', kw: 'new tab create blank', exec: 'new-tab' },
  {
    id: 'new-window',
    title: 'New Window',
    hint: 'Action',
    icon: 'app-window',
    kw: 'new window popup',
    exec: 'new-window',
  },
  {
    id: 'incognito',
    title: 'New Incognito Window',
    hint: 'Action',
    icon: 'sunglasses',
    kw: 'incognito private secret',
    exec: 'new-window',
    payload: { incognito: true },
  },
  {
    id: 'reopen',
    title: 'Reopen Closed Tab',
    hint: 'Action',
    icon: 'arrow-counter-clockwise',
    kw: 'reopen restore undo closed',
    exec: 'reopen-closed',
  },
  {
    id: 'duplicate',
    title: 'Duplicate Tab',
    hint: 'Tab',
    icon: 'copy',
    kw: 'duplicate clone copy tab',
    exec: 'duplicate',
  },
  { id: 'pin', title: 'Pin / Unpin Tab', hint: 'Tab', icon: 'push-pin', kw: 'pin unpin', exec: 'pin-toggle' },
  {
    id: 'mute',
    title: 'Mute / Unmute Tab',
    hint: 'Tab',
    icon: 'speaker-slash',
    kw: 'mute unmute sound audio',
    exec: 'mute-toggle',
  },
  { id: 'reload', title: 'Reload Tab', hint: 'Tab', icon: 'arrow-clockwise', kw: 'reload refresh', exec: 'reload' },
  {
    id: 'hard-reload',
    title: 'Hard Reload (bypass cache)',
    hint: 'Tab',
    icon: 'lightning',
    kw: 'hard reload cache refresh',
    exec: 'hard-reload',
  },
  { id: 'back', title: 'Go Back', hint: 'Navigate', icon: 'arrow-left', kw: 'back previous history', exec: 'go-back' },
  {
    id: 'forward',
    title: 'Go Forward',
    hint: 'Navigate',
    icon: 'arrow-right',
    kw: 'forward next history',
    exec: 'go-forward',
  },
  { id: 'close-tab', title: 'Close This Tab', hint: 'Tab', icon: 'x', kw: 'close delete tab', exec: 'close-tab' },
  {
    id: 'close-others',
    title: 'Close Other Tabs',
    hint: 'Tab',
    icon: 'broom',
    kw: 'close others',
    exec: 'close-others',
  },
  {
    id: 'close-right',
    title: 'Close Tabs to the Right',
    hint: 'Tab',
    icon: 'arrow-line-right',
    kw: 'close right',
    exec: 'close-right',
  },
  {
    id: 'close-dupes',
    title: 'Close Duplicate Tabs',
    hint: 'Tab',
    icon: 'trash',
    kw: 'close duplicate dedupe',
    exec: 'close-duplicates',
  },
  {
    id: 'move-window',
    title: 'Move Tab to New Window',
    hint: 'Tab',
    icon: 'arrow-square-out',
    kw: 'move pop out window',
    exec: 'move-to-new-window',
  },
  {
    id: 'group',
    title: 'Group / Ungroup Tab',
    hint: 'Tab',
    icon: 'stack',
    kw: 'group ungroup organize',
    exec: 'group-tab',
    requires: 'canGroup',
  },
  {
    id: 'discard',
    title: 'Unload (Discard) Tab to Save Memory',
    hint: 'Tab',
    icon: 'moon',
    kw: 'discard unload sleep memory suspend',
    exec: 'discard',
    requires: 'canDiscard',
  },
  {
    id: 'copy-url',
    title: 'Copy URL',
    hint: 'Clipboard',
    icon: 'link',
    kw: 'copy url link address',
    local: () => navigator.clipboard.writeText(location.href),
  },
  {
    id: 'copy-title',
    title: 'Copy Title + URL',
    hint: 'Clipboard',
    icon: 'clipboard-text',
    kw: 'copy title markdown',
    local: () => navigator.clipboard.writeText(`[${document.title}](${location.href})`),
  },
  {
    id: 'bookmark',
    title: 'Bookmark This Tab',
    hint: 'Action',
    icon: 'bookmark',
    kw: 'bookmark star favorite save',
    exec: 'bookmark-tab',
  },
  {
    id: 'screenshot',
    title: 'Screenshot Visible Area (PNG download)',
    hint: 'Action',
    icon: 'camera',
    kw: 'screenshot capture png image',
    exec: 'screenshot',
    before: beforeCapture,
  },
  {
    id: 'print',
    title: 'Print Page',
    hint: 'Action',
    icon: 'printer',
    kw: 'print pdf',
    pageOnly: true,
    local: () => window.print(),
  },
  {
    id: 'source',
    title: 'View Page Source',
    hint: 'Dev',
    icon: 'code',
    kw: 'source view html code',
    pageOnly: true,
    local: () => window.open('view-source:' + location.href, '_blank'),
  },
  {
    id: 'scroll-top',
    title: 'Scroll to Top',
    hint: 'Page',
    icon: 'arrow-up',
    kw: 'scroll top up',
    pageOnly: true,
    local: () => window.scrollTo({ top: 0, behavior: 'smooth' }),
  },
  {
    id: 'scroll-bottom',
    title: 'Scroll to Bottom',
    hint: 'Page',
    icon: 'arrow-down',
    kw: 'scroll bottom down',
    pageOnly: true,
    local: () => window.scrollTo({ top: document.body.scrollHeight, behavior: 'smooth' }),
  },
  {
    id: 'fullscreen',
    title: 'Toggle Fullscreen',
    hint: 'View',
    icon: 'corners-out',
    kw: 'fullscreen f11 present',
    pageOnly: true,
    local: () =>
      document.fullscreenElement ? document.exitFullscreen() : document.documentElement.requestFullscreen(),
  },
  {
    id: 'zoom-in',
    title: 'Zoom In',
    hint: 'View',
    icon: 'magnifying-glass-plus',
    kw: 'zoom in bigger',
    exec: 'zoom',
    payload: { delta: 0.1 },
  },
  {
    id: 'zoom-out',
    title: 'Zoom Out',
    hint: 'View',
    icon: 'magnifying-glass-minus',
    kw: 'zoom out smaller',
    exec: 'zoom',
    payload: { delta: -0.1 },
  },
  {
    id: 'zoom-reset',
    title: 'Reset Zoom',
    hint: 'View',
    icon: 'arrows-counter-clockwise',
    kw: 'zoom reset 100',
    exec: 'zoom',
    payload: { delta: 0 },
  },
  {
    id: 'pg-history',
    title: 'Open History',
    hint: 'Chrome',
    icon: 'clock',
    kw: 'history open chrome page',
    exec: 'chrome-page',
    payload: { page: 'history' },
  },
  {
    id: 'pg-downloads',
    title: 'Open Downloads',
    hint: 'Chrome',
    icon: 'download-simple',
    kw: 'downloads files chrome',
    exec: 'chrome-page',
    payload: { page: 'downloads' },
  },
  {
    id: 'pg-bookmarks',
    title: 'Open Bookmark Manager',
    hint: 'Chrome',
    icon: 'bookmarks-simple',
    kw: 'bookmarks manager chrome',
    exec: 'chrome-page',
    payload: { page: 'bookmarks' },
  },
  {
    id: 'pg-settings',
    title: 'Open Settings',
    hint: 'Chrome',
    icon: 'gear',
    kw: 'settings preferences chrome',
    exec: 'chrome-page',
    payload: { page: 'settings' },
  },
  {
    id: 'pg-extensions',
    title: 'Open Extensions',
    hint: 'Chrome',
    icon: 'puzzle-piece',
    kw: 'extensions plugins chrome',
    exec: 'chrome-page',
    payload: { page: 'extensions' },
  },
  {
    id: 'pg-passwords',
    title: 'Open Password Manager',
    hint: 'Chrome',
    icon: 'key',
    kw: 'password passkey login',
    exec: 'chrome-page',
    payload: { page: 'passwords' },
  },
  {
    id: 'pg-clear',
    title: 'Clear Browsing Data…',
    hint: 'Chrome',
    icon: 'eraser',
    kw: 'clear cache cookies data privacy',
    exec: 'chrome-page',
    payload: { page: 'clearData' },
  },
  {
    id: 'engine',
    title: 'Cycle Search Engine (Google→DDG→Bing→Perplexity)',
    hint: 'Settings',
    icon: 'magnifying-glass',
    kw: 'search engine google duckduckgo bing default',
  },
];

export const actionById = (id: string): Action | undefined => ACTIONS.find((a) => a.id === id);
